[package]
name = "arnis"
version = "2.1.1"
edition = "2021"
description = "Arnis - Generate real life cities in Minecraft"
homepage = "https://github.com/louis-e/arnis"
repository = "https://github.com/louis-e/arnis"
license = "GPL-3.0"
readme = "README.md"

[profile.release]
lto = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
clap = { version = "4.1", features = ["derive"] }
colored = "2.1.0"
dirs = "4.0.0"
fastanvil = "0.31.0"
fastnbt = "2.5.0"
flate2 = "1.0"
fnv = "1.0.7"
fs2 = "0.4"
geo = "0.28.0"
indicatif = "0.17.8"
itertools = "0.13.0"
nalgebra = "0.33.0"
once_cell = "1.19.0"
rand = "0.8.5"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
rfd = { version = "0.15.0", default-features = false }
semver = "1.0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2.0.0"
tauri-plugin-shell = "2"
tokio = { version = "1.42.0", features = ["full"] }
